apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}-secret
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
data:
  LWARE_IDENTITY_PASSWORD: {{ required "missing required value: .Values.secret.identity.password" .Values.secret.identity.password | b64enc }}
  {{- if .Values.secret.redis.password }}
  REDIS_PASSWORD: {{ .Values.secret.redis.password | b64enc }}
  {{- end }}
  MONGO_CONNECTION_STRING: {{ required "missing required value: .Values.secret.mongo.connectionString" .Values.secret.mongo.connectionString | b64enc }}
