{{- if .Values.webApp.enabled -}}
{{- if .Values.webApp.ingress.enabled -}}
{{- $fullName := include "<CHARTNAME>.webAppName" . -}}
{{- $svcPort := .Values.webApp.service.port -}}
{{- $ingressClassName := default .Values.global.ingress.className .Values.webApp.ingress.className -}}
{{- if and .Values.webApp.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) -}}
  {{- if not (hasKey .Values.webApp.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.webApp.ingress.annotations "kubernetes.io/ingress.class" $ingressClassName }}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "<CHARTNAME>.webAppLabels" . | nindent 4 }}
  {{- with .Values.webApp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  {{- if .Values.webApp.ingress.tls }}
  tls:
    {{- range .Values.webApp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webApp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .http.paths }}
          - path: {{ required "missing required value: .Values.webApp.ingress.hosts[*].http.paths.[*].path" (default $.Values.config.appUriPrefix .path) }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
