apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHARTNAME>.webServiceName" . }}
  labels:
    {{- include "<CHARTNAME>.webDeploymentLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
      protocol: {{ .Values.service.protocol }}
      name: http
  selector:
    {{- include "<CHARTNAME>.webSelectorLabels" . | nindent 4 }}
