FROM ghcr.io/licenseware/licenseware-sdk-v2:latest AS base

FROM base AS test

ENV ENV=test
COPY --chown=${USER} . .
RUN pip install -r requirements.txt

CMD ["./entrypoint.sh"]

FROM base AS stack

ENV ENV=stack
COPY --chown=${USER} . .
RUN pip install -r requirements.txt

CMD ["./entrypoint.sh"]

FROM base AS prod

ENV ENV=prod
RUN opentelemetry-bootstrap --action=install
COPY --chown=${USER} . .
RUN pip install -r requirements.txt

CMD ["./entrypoint.sh"]