name: Build docker image & push to Github registry

on:
  push:
    branches:
      - main
      - "releases/**"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set image tag
        run: |
          echo IMAGE_NAME={% raw %}${{ env.REGISTRY }}/${{ github.repository }}{% endraw %} >> $GITHUB_ENV

          if [[ "{% raw %}${{ github.ref_name }}{% endraw %}" == "main" ]]; then
            echo IMAGE_TAG=latest >> $GITHUB_ENV
          else
            echo IMAGE_TAG={% raw %}${{ github.ref_name }}{% endraw %} >> $GITHUB_ENV
          fi

      - name: Set up QEMU needed for Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: {% raw %}${{ env.REGISTRY }}{% endraw %}
          username: {% raw %}${{ github.actor }}{% endraw %}
          password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
          logout: false

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "{% raw %}${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}{% endraw %}"
          labels: |
            org.opencontainers.image.source $GITHUB_SERVER_URL/{% raw %}${{ github.repository }}{% endraw %}
