name: Build docker image & push to Github registry

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    # build the images daily (to keep everything up-to-date)
    - cron:  '0 0 * * *'
  pull_request:


env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: ${{ github.repository }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up QEMU needed for Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: run
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.head_ref || github.ref_name }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

      - name: Build and push ODBC image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_TAG }}-odbc
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.head_ref || github.ref_name }}-odbc
          target: odbc
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
