name: Build docker image & push to Github registry

on:
  push:
    branches:
      - main
      - "releases/**"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set image tag
        run: |
          echo IMAGE_NAME=${{ env.REGISTRY }}/${{ github.repository }} >> $GITHUB_ENV

          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo IMAGE_TAG=latest >> $GITHUB_ENV
          else
            echo IMAGE_TAG=${{ github.ref_name }} >> $GITHUB_ENV
          fi

      - name: Set up QEMU needed for Docker
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          labels: |
            org.opencontainers.image.source ${{ github.server_url }}/${{ github.repository }}
