name: linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8.5"
          architecture: "x64"

      - name: Run linters
        run: |
          pip install -U pip pre-commit
          pre-commit run -a

      - name: Commit linting changes
        if: failure()
        uses: EndBug/add-and-commit@v9.1.0
        with:
          message: "chore: lint 🚨"
          new_branch: ${{ github.head_ref || github.ref_name }}
