name: publish-pypi
on:
  release:
    types:
      - published

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: "3.8.5"
      - name: Prepare
        run: pip install wheel && python setup.py sdist bdist_wheel
      - name: Publish PyPi
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
