name: trivy-image-scan

on:
  pull_request:
  push:
    branches:
      - main

env:
  IMAGE_REPOSITORY: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  scan-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU needed for Docker
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          logout: false
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}
      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          format: sarif
          # ignore-unfixed: true
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}
          output: trivy-results.sarif
          severity: CRITICAL,HIGH
          vuln-type: os,library
      - if: always()
        name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
